code = input ('FISHING FRESHWATER BENDS AND SALTWATER COASTS REWARDS ANYONE FEELING STRESSED. RESOURCEFUL ANGLERS USUALLY FIND MASTERFUL LEAPERS FUN AND ADMIT SWORDFISH RANK OVERWHELMING ANYDAY? ') [0::3]
msg = ""
for i in code: msg += " " + i
print (msg [1:])